In [1]:
import requests
import pandas as pd
import numpy as np
import datetime

date = '20201029'
stock_no = '2330'
url = 'https://www.twse.com.tw/exchangeReport/STOCK_DAY?date=%s&stockNo=%s' % (date,stock_no)
res = requests.get(url)
res.text

'{"stat":"OK","date":"20201029","title":"109年10月 2330 台積電           各日成交資訊","fields":["日期","成交股數","成交金額","開盤價","最高價","最低價","收盤價","漲跌價差","成交筆數"],"data":[["109/10/05","33,238,832","14,450,407,588","438.00","438.00","431.50","432.50","-0.50","18,148"],["109/10/06","36,276,395","15,935,558,262","441.50","442.00","437.50","439.50","+7.00","20,189"],["109/10/07","44,691,239","19,693,987,093","435.00","445.00","435.00","443.00","+3.50","24,438"],["109/10/08","60,853,811","27,461,867,933","450.00","454.00","448.50","453.00","+10.00","37,378"],["109/10/12","67,645,223","31,061,721,030","458.00","462.00","457.50","460.00","+7.00","36,118"],["109/10/13","46,303,738","21,346,346,714","465.00","465.00","456.50","462.00","+2.00","25,938"],["109/10/14","52,677,241","24,157,138,176","460.50","461.00","457.00","459.00","-3.00","22,599"],["109/10/15","49,987,278","22,668,836,399","456.00","456.50","450.00","453.00","-6.00","23,794"],["109/10/16","48,274,801","21,775,749,575","451.00","456.00","448.50","449.00","-4.00","26,602"],["109/10/19","34,846,906","15,854,021,670","453.00","457.50","451.00","457.50","+8.50","17,112"],["109/10/20","26,567,638","12,065,806,730","455.50","457.00","451.00","451.00","-6.50","12,725"],["109/10/21","29,906,921","13,561,798,906","453.50","456.00","451.00","453.00","+2.00","15,490"],["109/10/22","25,285,547","11,435,937,453","450.00","455.00","449.50","455.00","+2.00","10,354"],["109/10/23","18,777,385","8,516,604,326","458.00","458.00","451.50","452.00","-3.00","9,909"],["109/10/26","15,800,622","7,136,001,014","455.00","455.00","450.00","450.00","-2.00","17,664"],["109/10/27","31,795,010","14,213,282,507","447.50","448.50","445.50","447.00","-3.00","30,644"],["109/10/28","26,221,663","11,660,544,725","445.00","447.00","443.00","444.00","-3.00","35,598"],["109/10/29","43,075,387","18,832,675,652","436.50","439.50","435.50","437.00","-7.00","55,027"],["109/10/30","49,770,771","21,614,729,093","437.00","437.00","432.00","432.00","-5.00","46,871"]],"notes":["符號說明:+/-/X表示漲/跌/不比價","當日統計資訊含一般、零股、盤後定價、鉅額交易，不含拍賣、標購。","ETF證券代號第六碼為K、M、S、C者，表示該ETF以外幣交易。"]}'

In [2]:
data = res.json()
data

{'stat': 'OK',
 'date': '20201029',
 'title': '109年10月 2330 台積電           各日成交資訊',
 'fields': ['日期', '成交股數', '成交金額', '開盤價', '最高價', '最低價', '收盤價', '漲跌價差', '成交筆數'],
 'data': [['109/10/05',
   '33,238,832',
   '14,450,407,588',
   '438.00',
   '438.00',
   '431.50',
   '432.50',
   '-0.50',
   '18,148'],
  ['109/10/06',
   '36,276,395',
   '15,935,558,262',
   '441.50',
   '442.00',
   '437.50',
   '439.50',
   '+7.00',
   '20,189'],
  ['109/10/07',
   '44,691,239',
   '19,693,987,093',
   '435.00',
   '445.00',
   '435.00',
   '443.00',
   '+3.50',
   '24,438'],
  ['109/10/08',
   '60,853,811',
   '27,461,867,933',
   '450.00',
   '454.00',
   '448.50',
   '453.00',
   '+10.00',
   '37,378'],
  ['109/10/12',
   '67,645,223',
   '31,061,721,030',
   '458.00',
   '462.00',
   '457.50',
   '460.00',
   '+7.00',
   '36,118'],
  ['109/10/13',
   '46,303,738',
   '21,346,346,714',
   '465.00',
   '465.00',
   '456.50',
   '462.00',
   '+2.00',
   '25,938'],
  ['109/10/14',
   '52,677,241',
   '24,157,138,176',
   '460.50',
   '461.00',
   '457.00',
   '459.00',
   '-3.00',
   '22,599'],
  ['109/10/15',
   '49,987,278',
   '22,668,836,399',
   '456.00',
   '456.50',
   '450.00',
   '453.00',
   '-6.00',
   '23,794'],
  ['109/10/16',
   '48,274,801',
   '21,775,749,575',
   '451.00',
   '456.00',
   '448.50',
   '449.00',
   '-4.00',
   '26,602'],
  ['109/10/19',
   '34,846,906',
   '15,854,021,670',
   '453.00',
   '457.50',
   '451.00',
   '457.50',
   '+8.50',
   '17,112'],
  ['109/10/20',
   '26,567,638',
   '12,065,806,730',
   '455.50',
   '457.00',
   '451.00',
   '451.00',
   '-6.50',
   '12,725'],
  ['109/10/21',
   '29,906,921',
   '13,561,798,906',
   '453.50',
   '456.00',
   '451.00',
   '453.00',
   '+2.00',
   '15,490'],
  ['109/10/22',
   '25,285,547',
   '11,435,937,453',
   '450.00',
   '455.00',
   '449.50',
   '455.00',
   '+2.00',
   '10,354'],
  ['109/10/23',
   '18,777,385',
   '8,516,604,326',
   '458.00',
   '458.00',
   '451.50',
   '452.00',
   '-3.00',
   '9,909'],
  ['109/10/26',
   '15,800,622',
   '7,136,001,014',
   '455.00',
   '455.00',
   '450.00',
   '450.00',
   '-2.00',
   '17,664'],
  ['109/10/27',
   '31,795,010',
   '14,213,282,507',
   '447.50',
   '448.50',
   '445.50',
   '447.00',
   '-3.00',
   '30,644'],
  ['109/10/28',
   '26,221,663',
   '11,660,544,725',
   '445.00',
   '447.00',
   '443.00',
   '444.00',
   '-3.00',
   '35,598'],
  ['109/10/29',
   '43,075,387',
   '18,832,675,652',
   '436.50',
   '439.50',
   '435.50',
   '437.00',
   '-7.00',
   '55,027'],
  ['109/10/30',
   '49,770,771',
   '21,614,729,093',
   '437.00',
   '437.00',
   '432.00',
   '432.00',
   '-5.00',
   '46,871']],
 'notes': ['符號說明:+/-/X表示漲/跌/不比價',
  '當日統計資訊含一般、零股、盤後定價、鉅額交易，不含拍賣、標購。',
  'ETF證券代號第六碼為K、M、S、C者，表示該ETF以外幣交易。']}

In [3]:
def get_stock_dayprice(date,stock_no):
    quote = []
    url = 'https://www.twse.com.tw/exchangeReport/STOCK_DAY?date=%s&stockNo=%s' % (date,stock_no)
    res = requests.get(url)
    data = res.json()
    return transform(data['data'])   
    # do date transform

def transform_data(data):
    print(data)
    data[0] = datetime.datetime.strptime( transform_date(data[0]), '%Y/%m/%d') 
    #transform day
    data[1] = int(data[1].replace(',',''))
    data[2] = int(data[2].replace(',',''))
    data[3] = float(data[3].replace(',',''))
    data[4] = float(data[4].replace(',',''))
    data[5] = float(data[5].replace(',',''))
    data[6] = float(data[6].replace(',',''))
    data[7] = float(0.0 if data[7].replace(',','') == 'X0.00' else data[7].replace(',',''))
    data[8] = int(data[8].replace(',',''))
    return data

def transform_date(date):
        y, m, d = date.split('/')
        return str(int(y)+1911) + '/' + m +'/' + d 

def transform(data):
    return [transform_data(d) for d in data]

df_s = get_stock_dayprice(date,stock_no)
df_s

['109/10/05', '33,238,832', '14,450,407,588', '438.00', '438.00', '431.50', '432.50', '-0.50', '18,148']
['109/10/06', '36,276,395', '15,935,558,262', '441.50', '442.00', '437.50', '439.50', '+7.00', '20,189']
['109/10/07', '44,691,239', '19,693,987,093', '435.00', '445.00', '435.00', '443.00', '+3.50', '24,438']
['109/10/08', '60,853,811', '27,461,867,933', '450.00', '454.00', '448.50', '453.00', '+10.00', '37,378']
['109/10/12', '67,645,223', '31,061,721,030', '458.00', '462.00', '457.50', '460.00', '+7.00', '36,118']
['109/10/13', '46,303,738', '21,346,346,714', '465.00', '465.00', '456.50', '462.00', '+2.00', '25,938']
['109/10/14', '52,677,241', '24,157,138,176', '460.50', '461.00', '457.00', '459.00', '-3.00', '22,599']
['109/10/15', '49,987,278', '22,668,836,399', '456.00', '456.50', '450.00', '453.00', '-6.00', '23,794']
['109/10/16', '48,274,801', '21,775,749,575', '451.00', '456.00', '448.50', '449.00', '-4.00', '26,602']
['109/10/19', '34,846,906', '15,854,021,670', '453.00', '457.50', '451.00', '457.50', '+8.50', '17,112']
['109/10/20', '26,567,638', '12,065,806,730', '455.50', '457.00', '451.00', '451.00', '-6.50', '12,725']
['109/10/21', '29,906,921', '13,561,798,906', '453.50', '456.00', '451.00', '453.00', '+2.00', '15,490']
['109/10/22', '25,285,547', '11,435,937,453', '450.00', '455.00', '449.50', '455.00', '+2.00', '10,354']
['109/10/23', '18,777,385', '8,516,604,326', '458.00', '458.00', '451.50', '452.00', '-3.00', '9,909']
['109/10/26', '15,800,622', '7,136,001,014', '455.00', '455.00', '450.00', '450.00', '-2.00', '17,664']
['109/10/27', '31,795,010', '14,213,282,507', '447.50', '448.50', '445.50', '447.00', '-3.00', '30,644']
['109/10/28', '26,221,663', '11,660,544,725', '445.00', '447.00', '443.00', '444.00', '-3.00', '35,598']
['109/10/29', '43,075,387', '18,832,675,652', '436.50', '439.50', '435.50', '437.00', '-7.00', '55,027']
['109/10/30', '49,770,771', '21,614,729,093', '437.00', '437.00', '432.00', '432.00', '-5.00', '46,871']

[[datetime.datetime(2020, 10, 5, 0, 0),
  33238832,
  14450407588,
  438.0,
  438.0,
  431.5,
  432.5,
  -0.5,
  18148],
 [datetime.datetime(2020, 10, 6, 0, 0),
  36276395,
  15935558262,
  441.5,
  442.0,
  437.5,
  439.5,
  7.0,
  20189],
 [datetime.datetime(2020, 10, 7, 0, 0),
  44691239,
  19693987093,
  435.0,
  445.0,
  435.0,
  443.0,
  3.5,
  24438],
 [datetime.datetime(2020, 10, 8, 0, 0),
  60853811,
  27461867933,
  450.0,
  454.0,
  448.5,
  453.0,
  10.0,
  37378],
 [datetime.datetime(2020, 10, 12, 0, 0),
  67645223,
  31061721030,
  458.0,
  462.0,
  457.5,
  460.0,
  7.0,
  36118],
 [datetime.datetime(2020, 10, 13, 0, 0),
  46303738,
  21346346714,
  465.0,
  465.0,
  456.5,
  462.0,
  2.0,
  25938],
 [datetime.datetime(2020, 10, 14, 0, 0),
  52677241,
  24157138176,
  460.5,
  461.0,
  457.0,
  459.0,
  -3.0,
  22599],
 [datetime.datetime(2020, 10, 15, 0, 0),
  49987278,
  22668836399,
  456.0,
  456.5,
  450.0,
  453.0,
  -6.0,
  23794],
 [datetime.datetime(2020, 10, 16, 0, 0),
  48274801,
  21775749575,
  451.0,
  456.0,
  448.5,
  449.0,
  -4.0,
  26602],
 [datetime.datetime(2020, 10, 19, 0, 0),
  34846906,
  15854021670,
  453.0,
  457.5,
  451.0,
  457.5,
  8.5,
  17112],
 [datetime.datetime(2020, 10, 20, 0, 0),
  26567638,
  12065806730,
  455.5,
  457.0,
  451.0,
  451.0,
  -6.5,
  12725],
 [datetime.datetime(2020, 10, 21, 0, 0),
  29906921,
  13561798906,
  453.5,
  456.0,
  451.0,
  453.0,
  2.0,
  15490],
 [datetime.datetime(2020, 10, 22, 0, 0),
  25285547,
  11435937453,
  450.0,
  455.0,
  449.5,
  455.0,
  2.0,
  10354],
 [datetime.datetime(2020, 10, 23, 0, 0),
  18777385,
  8516604326,
  458.0,
  458.0,
  451.5,
  452.0,
  -3.0,
  9909],
 [datetime.datetime(2020, 10, 26, 0, 0),
  15800622,
  7136001014,
  455.0,
  455.0,
  450.0,
  450.0,
  -2.0,
  17664],
 [datetime.datetime(2020, 10, 27, 0, 0),
  31795010,
  14213282507,
  447.5,
  448.5,
  445.5,
  447.0,
  -3.0,
  30644],
 [datetime.datetime(2020, 10, 28, 0, 0),
  26221663,
  11660544725,
  445.0,
  447.0,
  443.0,
  444.0,
  -3.0,
  35598],
 [datetime.datetime(2020, 10, 29, 0, 0),
  43075387,
  18832675652,
  436.5,
  439.5,
  435.5,
  437.0,
  -7.0,
  55027],
 [datetime.datetime(2020, 10, 30, 0, 0),
  49770771,
  21614729093,
  437.0,
  437.0,
  432.0,
  432.0,
  -5.0,
  46871]]

In [7]:
#pandas 轉資料成DataFrame
s = pd.DataFrame(df_s)
s.columns = ['date','shares','amount','open','high','low','close','change','turnover']
s
#索引改成日期才能照日期分析
#新增月份欄位(月份分析)

,date,shares,amount,open,high,low,close,change,turnover
0,2020-10-05,33238832,14450407588,438.0,438.0,431.5,432.5,-0.5,18148
1,2020-10-06,36276395,15935558262,441.5,442.0,437.5,439.5,7.0,20189
2,2020-10-07,44691239,19693987093,435.0,445.0,435.0,443.0,3.5,24438
3,2020-10-08,60853811,27461867933,450.0,454.0,448.5,453.0,10.0,37378
4,2020-10-12,67645223,31061721030,458.0,462.0,457.5,460.0,7.0,36118
5,2020-10-13,46303738,21346346714,465.0,465.0,456.5,462.0,2.0,25938
6,2020-10-14,52677241,24157138176,460.5,461.0,457.0,459.0,-3.0,22599
7,2020-10-15,49987278,22668836399,456.0,456.5,450.0,453.0,-6.0,23794
8,2020-10-16,48274801,21775749575,451.0,456.0,448.5,449.0,-4.0,26602
9,2020-10-19,34846906,15854021670,453.0,457.5,451.0,457.5,8.5,17112
10,2020-10-20,26567638,12065806730,455.5,457.0,451.0,451.0,-6.5,12725
11,2020-10-21,29906921,13561798906,453.5,456.0,451.0,453.0,2.0,15490
12,2020-10-22,25285547,11435937453,450.0,455.0,449.5,455.0,2.0,10354
13,2020-10-23,18777385,8516604326,458.0,458.0,451.5,452.0,-3.0,9909
14,2020-10-26,15800622,7136001014,455.0,455.0,450.0,450.0,-2.0,17664
15,2020-10-27,31795010,14213282507,447.5,448.5,445.5,447.0,-3.0,30644
16,2020-10-28,26221663,11660544725,445.0,447.0,443.0,444.0,-3.0,35598
17,2020-10-29,43075387,18832675652,436.5,439.5,435.5,437.0,-7.0,55027
18,2020-10-30,49770771,21614729093,437.0,437.0,432.0,432.0,-5.0,46871

In [9]:
s['stock_no'] = pd.Series(stock_no ,index = s.index)
s   #s.index 0~19 step by 1

,date,shares,amount,open,high,low,close,change,turnover,stock_no
0,2020-10-05,33238832,14450407588,438.0,438.0,431.5,432.5,-0.5,18148,2330
1,2020-10-06,36276395,15935558262,441.5,442.0,437.5,439.5,7.0,20189,2330
2,2020-10-07,44691239,19693987093,435.0,445.0,435.0,443.0,3.5,24438,2330
3,2020-10-08,60853811,27461867933,450.0,454.0,448.5,453.0,10.0,37378,2330
4,2020-10-12,67645223,31061721030,458.0,462.0,457.5,460.0,7.0,36118,2330
5,2020-10-13,46303738,21346346714,465.0,465.0,456.5,462.0,2.0,25938,2330
6,2020-10-14,52677241,24157138176,460.5,461.0,457.0,459.0,-3.0,22599,2330
7,2020-10-15,49987278,22668836399,456.0,456.5,450.0,453.0,-6.0,23794,2330
8,2020-10-16,48274801,21775749575,451.0,456.0,448.5,449.0,-4.0,26602,2330
9,2020-10-19,34846906,15854021670,453.0,457.5,451.0,457.5,8.5,17112,2330
10,2020-10-20,26567638,12065806730,455.5,457.0,451.0,451.0,-6.5,12725,2330
11,2020-10-21,29906921,13561798906,453.5,456.0,451.0,453.0,2.0,15490,2330
12,2020-10-22,25285547,11435937453,450.0,455.0,449.5,455.0,2.0,10354,2330
13,2020-10-23,18777385,8516604326,458.0,458.0,451.5,452.0,-3.0,9909,2330
14,2020-10-26,15800622,7136001014,455.0,455.0,450.0,450.0,-2.0,17664,2330
15,2020-10-27,31795010,14213282507,447.5,448.5,445.5,447.0,-3.0,30644,2330
16,2020-10-28,26221663,11660544725,445.0,447.0,443.0,444.0,-3.0,35598,2330
17,2020-10-29,43075387,18832675652,436.5,439.5,435.5,437.0,-7.0,55027,2330
18,2020-10-30,49770771,21614729093,437.0,437.0,432.0,432.0,-5.0,46871,2330

In [10]:
print(s.groupby('stock_no').shares.sum())   #月成交

stock_no
2330    741996408
Name: shares, dtype: int64

In [11]:
s.to_csv('C:\\Users\\USER\\Desktop\\興趣自我\\資料庫\\SQLiteStudio\\股票\\23302010.csv')